### ISSUE TITLE
 绑定失败，Server disconnected without sending a response.

### ISSUE THREAD

**Issue by Lee-7723** [nek0us/nonebot_plugin_steam_game_status#13]
绑定失败，Server disconnected without sending a response.
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/52600662/b7af96d5-3699-4d7e-8e7d-58c62c64d77a)
试了下在服务器可以ping到api的域名，但是与在本机ping到的不同。
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/52600662/ef750ea1-f096-446a-846a-a4b952fe6631)
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/52600662/4df6b726-f205-496a-a194-f6f7c0c6a6dc)

**Comment by nek0us** [comment]
curl一下呢？参考这个 #6

**Comment by Lee-7723** [comment]
在服务器curl半天不出东西，在本机是这样的
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/52600662/a2e4d101-e6e5-46dd-8bcb-65d64266499e)

**Comment by nek0us** [comment]
等晚上我更新一下

**Comment by Lee-7723** [comment]
刚刚让群友绑定了下试了试，确实也是多绑定几次就可以绑定上，播报功能还没做大量测试（能不能把句尾的“了”去了，读起来怪怪的）

**Comment by nek0us** [comment]
可以在python环境的包里找到插件目录，在init文件里全局搜索"了"替换为空就好
