### ISSUE TITLE
Steam id绑定失败

### ISSUE THREAD

**Issue by PackageInstaller** [nek0us/nonebot_plugin_steam_game_status#15]
`xxxx绑定失败，403 <html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>`

**Comment by nek0us** [comment]
插件版本是

**Comment by PackageInstaller** [comment]
最新git

**Comment by nek0us** [comment]
配置文件里的key格式呢

**Comment by PackageInstaller** [comment]
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/80018096/97cb4bda-c446-4751-9506-f4c3b8eb2969)

**Comment by PackageInstaller** [comment]
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/80018096/b5aa9f6d-3cc6-4727-95d3-cbe9aa650076)
后台警告

**Comment by nek0us** [comment]
我没复现出来，加一下我的企鹅吧，账号是 nekous加企鹅邮箱后缀

**Comment by CCYellowStar2** [comment]
同样报错

**Comment by CCYellowStar2** [comment]
破案了，key必须用列表形式
