### ISSUE TITLE
get game name failed

### ISSUE THREAD

**Issue by zym27187** [nek0us/nonebot_plugin_steam_game_status#19]
02-29 18:42:00 [INFO] apscheduler | Running job "now_steam (trigger: cron[minute='*/3'], next run at: 2024-02-29 18:45:00 CST)" (scheduled at 2024-02-29 18:42:00+08:00)
02-29 18:42:00 [ERROR] nonebot_plugin_steam_game_status | get game name failed.('Error attempting to encode "{\'1\': \'schinese\', \'3\': \'CN\', \'4\': 1}" as message: Unknown type: string', <traceback object at 0x000001E8148B63C0>)
02-29 18:42:00 [ERROR] nonebot_plugin_steam_game_status | get game name failed.('Error attempting to encode "{\'1\': \'schinese\', \'3\': \'CN\', \'4\': 1}" as message: Unknown type: string', <traceback object at 0x000001E8147829C0>)

![W70U4{Y6CNEGU2K~SUS3`J3](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/33774137/9dd064ff-0756-484d-8e29-9a7fc6c36e95)

**Comment by nek0us** [comment]
播报是正常的吗？这个可能是合并过来的代码的日志等级设置的不合适，对于没有中文名的游戏，获取失败时会输出error

**Comment by zym27187** [comment]
不能正常播报消息，相同订阅配置回滚至分支‘09fd2a54e30913e07eef045668997d4f1cd7a989’，可以播报消息

以下是steam_user_list.json完整内容：
{"76561198264351848": [28486866, "\u96c0\u9b42\u9ebb\u5c06(MahjongSoul)", "\u6ca1\u4eba\u627e\u6211\u4e38.jpg"]}

已知报错信息：02-29 21:13:00 [ERROR] nonebot_plugin_steam_game_status | get game name failed.('Error attempting to encode "{\'1\': \'schinese\', \'3\': \'CN\', \'4\': 1}" as message: Unknown type: string', <traceback object at 0x000002B595B20A40>)

定时任务‘now_steam’正常执行完成，无其他明显报错信息

**Comment by zym27187** [comment]
02-29 21:33:01 [DEBUG] nonebot_plugin_steam_game_status | steam id:76561198264351848 查询状态失败，module 'nonebot_plugin_sendmsg_by_bots.tools' has no attribute 'send_group_msg_by_bots_once'

**Comment by zym27187** [comment]
是的

**Comment by nek0us** [comment]
```bash
pip install nonebot_plugin_sendmsg_by_bots -U
```

**Comment by zym27187** [comment]
> ```shell
> pip install nonebot_plugin_sendmsg_by_bots -U
> ```

感谢   可以正常播报了    但是get game name failed的错误日志还存在

**Comment by nek0us** [comment]
> > ```shell
> > pip install nonebot_plugin_sendmsg_by_bots -U
> > ```
> 
> 感谢 可以正常播报了 但是get game name failed的错误日志还存在

你可以先把 插件 __init__.py 374 行的 logger.error 改成 logger.debug ，
这个小问题会在下个小版本修复

**Comment by zym27187** [comment]
> > > ```shell
> > > pip install nonebot_plugin_sendmsg_by_bots -U
> > > ```
> > 
> > 
> > 感谢 可以正常播报了 但是get game name failed的错误日志还存在
> 
> 你可以先把 插件 **init**.py 374 行的 logger.error 改成 logger.debug ， 这个小问题会在下个小版本修复

了解，issue先close了
