### ISSUE TITLE
希望可以添加游戏启动黑名单功能

### ISSUE THREAD

**Issue by Shattered217** [nek0us/nonebot_plugin_steam_game_status#21]
在有些情况，例如CS2平台（打完一局都会重启游戏），VR Chat（启动需要四个软件），会频繁触发通知推送，故希望添加游戏启动黑名单功能

**Comment by nek0us** [comment]
有这个计划，我得去多查查接口，因为api返回过来的只会是一个游戏。下次更新的时候改善。

**Comment by nek0us** [comment]
已更新

**Comment by Shattered217** [comment]
万分感谢！😍
