### ISSUE TITLE
定时任务警告？：Execution of job "now_steam 

### ISSUE THREAD

**Issue by Agnes4m** [nek0us/nonebot_plugin_steam_game_status#3]
`04-07 00:01:57 [WARNING] apscheduler | Execution of job "now_steam (trigger: interval[0:01:00], next run at: 2023-04-07 00:01:57 CST)" skipped: maximum number of running instances reached (1)`
python3.9.12,nonebot2.0.0rc3,插件是最新版本，当绑定后，并且开启播报后，如果没有任何变化，会弹出这个警告，我认为可以优化，捕捉状态，在log输出没有变化

**Comment by nek0us** [comment]
![T% J2%OLH`0JIK)GE4H_Z7B](https://user-images.githubusercontent.com/57703506/230520845-acc16ec6-5949-454d-9531-7a18cc93bc65.png)
![SGOU5QQKTNPZQGXQ8YIC6PJ](https://user-images.githubusercontent.com/57703506/230520853-fc766018-c218-4998-aea6-1f20c1aef34b.png)
![L`7_) KEQE8%}AW5M8(4TS2](https://user-images.githubusercontent.com/57703506/230522899-ec10b4db-a926-470d-90ae-dd74d3c7c511.png)
我构建了同样的环境，但没有复现出这个问题，可以描述一下更多细节吗？
比如有没有重复导入插件，已经绑定的steam id数量，服务器直接访问拼接后的steam api url的响应时间等等

**Comment by Umamusume-Agnes-Digital** [comment]
并没有重复导入（重复导入nb端会直接报错终止），我只绑定了一个steamid，响应时间130.368509ms。

准确来说情况就是有时候发不出消息，而且确认没有被风控或者禁言，例如我启动了steam一个游戏，我在两个群里开了播报，但是实际上除了概率正常外，可能只有一个会发出信息，另外一个不发送信息，nb端没有报错，gocq端也看不到任何消息错误。

**Comment by alloces52** [comment]
同样存在这个问题，似乎是apscheduler插件同时只能存在一个任务的原因
https://github.com/nonebot/plugin-apscheduler/issues/3

**Comment by nek0us** [comment]
用最新版试试
