### ISSUE TITLE
绑定完成 但是无响应

### ISSUE THREAD

**Issue by ArcPav** [nek0us/nonebot_plugin_steam_game_status#4]
![QQ图片20230407133909](https://user-images.githubusercontent.com/76981036/230548347-741e129a-02de-4742-b9a7-0cbceba2d4be.png)
![QQ图片20230407134107](https://user-images.githubusercontent.com/76981036/230548448-374ee8e5-b5b5-4239-a905-c78632b21fb5.png)

如图 上了游戏后并没有反应
一开始以为是游戏详情开的仅限好友 但是key是自己的 不应该因为仅限好友而无效
我把详情设为了公开还是没反应 只对特定游戏生效？

![QQ图片20230407134703](https://user-images.githubusercontent.com/76981036/230549183-3055f7bd-9aa2-4eb1-a6b0-e1c91ed2972b.png)

**Comment by nek0us** [comment]
steam在线状态是隐身吗
