### ISSUE TITLE
绑定失败

### ISSUE THREAD

**Issue by AyanamiYozi** [nek0us/nonebot_plugin_steam_game_status#6]
![4eb080ae6240a89fd9c7c15b3bfbb7d](https://user-images.githubusercontent.com/115979742/233940094-0bcf4586-4e26-4d11-b5db-840b8ca6d13e.png)
![image](https://user-images.githubusercontent.com/115979742/233940269-70d814cb-1905-41bc-8055-2676527fb9f4.png)

**Comment by nek0us** [comment]
这个错误是http没有正常响应造成的，在bot运行环境的命令工具里测试一下 
```bash
curl -i -s "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=KEY&steamids=ID"
# KEY 和 ID 替换为自己的
```
看看返回的状态码呢

**Comment by AyanamiYozi** [comment]
![image](https://user-images.githubusercontent.com/115979742/233956519-0623cf5f-95c7-4a28-b3c9-bffb5ea86d19.png)
请问是这样子吗？

**Comment by nek0us** [comment]
powershell下使用
```bash
 Invoke-WebRequest -Uri "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=KEY&steamids=ID"
 ```

**Comment by AyanamiYozi** [comment]
![$~)1@MB(%E{1I3}BBO2C${U](https://user-images.githubusercontent.com/115979742/234018842-8bec3d85-bc7d-4690-b631-1c849aa302ee.png)
是这样子吗

**Comment by nek0us** [comment]
最新版优化了一些日志输出，可以尝试使用最新版然后看一下日志

**Comment by AyanamiYozi** [comment]
![2877dfeb61fd249ea399e74728b983b](https://user-images.githubusercontent.com/115979742/236666088-c0ece6a5-260c-4791-b8a9-011cbba9216c.jpg)
![58d27a1a7d9935361bb8f2ea461a1ee](https://user-images.githubusercontent.com/115979742/236666094-c7b05fd6-dd6e-4503-8cec-ed0333e22017.png)
![5cb4863810577eb738832b810acc9e3](https://user-images.githubusercontent.com/115979742/236666096-4a59c64d-deee-4a2c-97b0-7c559151ccce.png)
这些可以吗

**Comment by nek0us** [comment]
是不是有使用steam++这类加速steam的工具？

**Comment by nek0us** [comment]
试一试0.0.10版本吧

**Comment by AyanamiYozi** [comment]
为了避免产生影响我在绑定的时候是将steam++关掉了的

**Comment by AyanamiYozi** [comment]
好吧，是我的问题，刚刚测试的时候忘记关了。现在问题解决了，谢谢，麻烦了
