### ISSUE TITLE
开始玩游戏后群内没有播报

### ISSUE THREAD

**Issue by PackageInstaller** [nek0us/nonebot_plugin_steam_game_status#7]
用的是zhenxun_bot，key填到了.env.dev中，id已绑定，已开启群播报，但是没任何播报信息
![Screenshot_20230424_212143](https://user-images.githubusercontent.com/80018096/234009237-e17679ba-c68f-4e20-a564-7af6027db4b1.png)

**Comment by PackageInstaller** [comment]
看起来是linux端的steam不会播报，用windows虚拟机试了下播报了

**Comment by nek0us** [comment]
linux端我没有测试过，已加入注意事项，感谢反馈，未来有空我再看一下这个

**Comment by PackageInstaller** [comment]
> linux端我没有测试过，已加入注意事项，感谢反馈，未来有空我再看一下这个

而且只会播报群主的，群友是win端没反应

**Comment by nek0us** [comment]
nonebot版本是？更新一下最新版，游戏状态的刷新时间是1分钟一次，看一下控制台日志有没有群员游玩消息发送失败的异常输出

**Comment by PackageInstaller** [comment]
我用的是基于nb的真寻bot,看了下list是2.0.0rc4，控制台和gocq端没有异常输出

**Comment by nek0us** [comment]
抱歉，我也想不明白原因，你可以尝试把插件更新到最新，删除 data/steam_group/group_list.json 文件（记得备份），然后在群内重新绑定试试

**Comment by PackageInstaller** [comment]
已更新，已删除重新绑定，开启群播报，群友（管理员）win端不显示播报，机器人后台和gocq未见任何异常

**Comment by 050644zf** [comment]
> 已更新，已删除重新绑定，开启群播报，群友（管理员）win端不显示播报，机器人后台和gocq未见任何异常

+1

**Comment by PackageInstaller** [comment]
重新来说一下情况，不知道怎么回事我linux端的steam是隐身状态的，今天才发现，可以播报了，群友的也能播报了

**Comment by PackageInstaller** [comment]
那我closelo
